// removing this module exports makes bug disappear
module.exports = {
  // even removing some unused constants here make bug disappear
  PRODUCT_ADDING_FAILED_BUS_EVENT_TYPE: 'PRODUCT_ADDING_FAILED',
  PRODUCT_ADDED_BUS_EVENT_TYPE: 'PRODUCT_ADDED',
  PRODUCT_DELETED_BUS_EVENT_TYPE: 'DELETE_PRODUCT',
  BASKET_FRAGMENT_RENDERED: 'BASKET_FRAGMENT_RENDERED',
  CHECKOUT_INFORMATION_DETERMINED: 'CHECKOUT_INFORMATION_DETERMINED',
  SHOW_PRODUCT_DETAILS: 'SHOW_PRODUCT_DETAILS',
  PRODUCT_INFO_FRAGMENT_RENDERED: 'PRODUCT_INFO_FRAGMENT_RENDERED',
  CART_LOADED_EVENT: 'CART_LOADED_EVENT',
  CART_VIEW_EVENT: 'CART_VIEW_EVENT',
  CART_SHIPPING_INFO_BUS_EVENT: 'CART_SHIPPING_INFO',
  HIDE_SHIPPING_INFO_BUS_EVENT: 'HIDE_SHIPPING_INFO',
  CHECKOUT_SUMMARY_PAGE_BUS_EVENT: 'CHECKOUT_SUMMARY',
  CHECKOUT_SUBMITTED_PAGE_BUS_EVENT: 'CHECKOUT_SUBMITTED',
  SHIPPING_INFO_SUBMIT_BUS_EVENT: 'SHIPPING_INFO_SUBMIT',
  CART_SELECT_DELIVERY_METHOD: 'SELECT_DELIVERY_METHOD',
  DELIVERY_ADDRESS_UPDATED_AND_VALIDATED_EVENT: 'DELIVERY_ADDRESS_UPDATED_AND_VALIDATED_EVENT',
  OPEN_STOCK_FINDER: 'OPEN_STOCK_FINDER',
  PURCHASE_COMPLETE_BUS_EVENT: 'PURCHASE_COMPLETE',
  DELIVERY_COST_TOOLTIP_OPENED: 'DELIVERY_COST_TOOLTIP_OPENED',
  PRODUCT_ADDED_FROM_PDP_MAIN_CTA: 'PDP_ADD_SHIPPING_MAIN_CTA',
  PRODUCT_ADDED_FROM_PDP_STORE_LOCATOR: 'PDP_ADD_PICKUP_STORE_LOCATOR',
  PRODUCT_ADDED_FROM_CART_ADD_PLUS: 'CART_ADD_PLUS'
}
